# 🏚️ clickhouse-helm: Production-ready Helm chart for deploying ClickHouse onto a Kubernetes cluster! ヽ(>∀<☆)ノ
# Copyright © 2022 Noel <cutie@floofy.dev>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: clickhouse
description: "Production-ready Helm chart for deploying ClickHouse onto a Kubernetes cluster! ヽ(>∀<☆)ノ"
apiVersion: v2
kubeVersion: ">=1.22"
appVersion: '22.4.5.9'
version: '1.0.0'
icon: https://clickhouse.com/wp-content/themes/clickhouse/images/favicon/favicon.ico
home: https://clickhouse.com
maintainers:
  - name: Noel
    email: cutie@floofy.dev
    url: https://floofy.dev
sources:
  - https://github.com/auguwu/clickhouse-helm
  - https://github.com/ClickHouse/ClickHouse
dependencies:
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 9.2.0
    condition: zookeeper.enabled
    tags:
      - zookeeper
